server:
  port: 8061
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_ums?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  redis:
    host: 172.16.116.100
    port: 6381
mybatis-plus:
  mapper-locations: classpath:mapper/ums/*.xml  # 读取映射文件
  global-config:
    db-config:
      id-type: auto  # 默认使用数据库自增
